// Generated by website-builder from design-repo/tokens/ (source: https://www.exante.app/). Tailwind v3. Do not hand-edit; re-run the scrape.
// Values are measured from computed styles; names are heuristic. Nothing here overrides Tailwind's default scales.
// Breakpoints: bp-<px> = min-width, bp-max-<px> = max-width (assumed min-width (no CSS was saved)).
export default {
  corePlugins: { preflight: false }, // the site's own CSS is the reset
  "content": [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx,html}"
  ],
  "theme": {
    "extend": {
      "colors": {
        "neutral-01": "rgb(0,0,0)",
        "neutral-02": "rgb(30,33,30)",
        "neutral-03": "rgb(255,255,255)",
        "blue-01": "rgb(0,0,238)",
        "neutral-04": "rgb(34,34,34)",
        "green-01": "rgb(144,252,149)",
        "neutral-05": "rgb(251,250,249)",
        "neutral-06": "rgba(30,33,30,0.6)",
        "orange-01": "rgb(242,236,232)",
        "neutral-07": "rgba(255,255,255,0.15)",
        "neutral-08": "rgb(118,118,118)",
        "neutral-09": "rgb(138,138,138)",
        "neutral-10": "rgb(250,250,250)",
        "neutral-11": "rgba(255,255,255,0.8)",
        "neutral-12": "rgba(30,33,30,0.8)",
        "neutral-13": "rgba(245,243,242,0.3)",
        "neutral-14": "rgba(0,0,0,0.7)",
        "neutral-15": "rgba(255,255,255,0.01)",
        "neutral-16": "rgb(249,250,251)",
        "green-02": "rgb(33,54,34)",
        "neutral-17": "rgba(0,0,0,0.4)",
        "neutral-18": "rgba(30,33,30,0.3)",
        "surface-default": "rgb(255,255,255)",
        "surface-alt": "rgb(30,33,30)",
        "surface-inverse": "rgb(30,33,30)",
        "surface-accent": "rgb(144,252,149)",
        "text-primary": "rgb(0,0,0)",
        "text-secondary": "rgb(30,33,30)",
        "text-inverse": "rgb(255,255,255)",
        "text-accent": "rgb(0,0,238)",
        "border-default": "rgb(118,118,118)",
        "accent-primary": "rgb(0,0,238)"
      },
      "spacing": {
        "sp-1": "1px",
        "sp-2": "2px",
        "sp-3": "3px",
        "sp-4": "4px",
        "sp-8": "8px",
        "sp-10": "10px",
        "sp-11": "11px",
        "sp-12": "12px",
        "sp-13": "13px",
        "sp-14": "14px",
        "sp-16": "16px",
        "sp-20": "20px",
        "sp-24": "24px",
        "sp-24_9723": "24.9723px",
        "sp-28": "28px",
        "sp-32": "32px",
        "sp-34": "34px",
        "sp-36": "36px",
        "sp-40": "40px",
        "sp-48": "48px",
        "sp-64": "64px",
        "sp-80": "80px",
        "sp-96": "96px",
        "sp-160": "160px",
        "gutter": "40px"
      },
      "borderRadius": {
        "r-4": "4px",
        "r-2": "2px",
        "r-8": "8px",
        "r-64": "64px",
        "r-16": "16px",
        "r-50": "50px",
        "r-10": "10px",
        "r-1": "1px",
        "control": "2px",
        "surface": "4px"
      },
      "boxShadow": {
        "e-01": "rgba(0, 0, 0, 0) 0px 0px 0px 1px inset",
        "elev-default": "rgba(0, 0, 0, 0) 0px 0px 0px 1px inset"
      },
      "fontFamily": {
        "ff-01": [
          "\"Geist Variable\"",
          "sans-serif"
        ],
        "ff-02": [
          "\"Alliance No.2 Regular\"",
          "sans-serif"
        ],
        "ff-03": [
          "\"Geist Mono\"",
          "sans-serif"
        ],
        "ff-04": [
          "\"Geist\"",
          "sans-serif"
        ],
        "ff-05": [
          "\"Alliance No.2 Light\"",
          "sans-serif"
        ],
        "ff-06": [
          "\"Chivo Mono\"",
          "sans-serif"
        ],
        "ff-07": [
          "\"Inter\"",
          "sans-serif"
        ],
        "display": [
          "\"Inter\"",
          "sans-serif"
        ],
        "heading": [
          "\"Geist Mono\"",
          "sans-serif"
        ],
        "body": [
          "\"Geist Variable\"",
          "sans-serif"
        ],
        "label": [
          "\"Geist Variable\"",
          "sans-serif"
        ]
      },
      "fontSize": {
        "fs-12": "12px",
        "fs-14": "14px",
        "fs-16": "16px",
        "fs-17": "17px",
        "fs-19": "19px",
        "fs-21": "21px",
        "fs-24": "24px",
        "fs-28": "28px",
        "fs-32": "32px",
        "fs-40": "40px",
        "fs-52": "52px",
        "fs-58": "58px",
        "fs-72": "72px",
        "fs-80": "80px",
        "display": [
          "16px",
          {
            "lineHeight": "19.2px",
            "fontWeight": "400"
          }
        ],
        "heading": [
          "32px",
          {
            "lineHeight": "38.4px",
            "fontWeight": "400"
          }
        ],
        "body": [
          "19px",
          {
            "lineHeight": "26.6px",
            "fontWeight": "400"
          }
        ],
        "label": [
          "19px",
          {
            "lineHeight": "26.6px",
            "fontWeight": "400"
          }
        ]
      },
      "transitionDuration": {
        "d-1300ms": "1.3s",
        "d-250ms": "0.25s",
        "d-400ms": "0.4s",
        "d-1500ms": "1.5s",
        "motion-default": "1.3s"
      },
      "transitionTimingFunction": {
        "ease-01": "cubic-bezier(0.44, 0, 0.13, 0.96)",
        "ease-02": "cubic-bezier(0.215, 0.61, 0.355, 1)",
        "ease-03": "linear",
        "motion-default": "cubic-bezier(0.44, 0, 0.13, 0.96)"
      },
      "screens": {
        "bp-759": {
          "min": "759px"
        },
        "bp-759.98": {
          "min": "759.98px"
        },
        "bp-760": {
          "min": "760px"
        },
        "bp-1099.98": {
          "min": "1099.98px"
        },
        "bp-1100": {
          "min": "1100px"
        },
        "bp-1439": {
          "min": "1439px"
        },
        "bp-1439.98": {
          "min": "1439.98px"
        }
      },
      "maxWidth": {
        "content": "1360px"
      }
    }
  },
  "plugins": []
};
