// Content Section — the section's real markup, read from the rendered page (route /legal/terms-of-service, section 2).
export default function ContentSection2() {
  return (
    <section className="framer-xw4pib" data-framer-appear-id="xw4pib" data-framer-name="Content Section" style={{ "opacity": "0.001", "transform": "translateY(60px) scale(0.95)" }} data-clone-section="ContentSection2">
      <div className="framer-62js3v" data-framer-name="Container">
        <div className="framer-18n3esr" data-framer-name="Column">
          <div className="framer-islu4v" data-framer-name="Information">
            <div className="framer-m25ep2" data-framer-name="About">
              <div className="framer-zh4osg" data-framer-component-type="RichTextContainer" style={{ "transform": "none" }}>
                <p className="framer-text framer-styles-preset-s1itte" data-styles-preset="n8sHGvPQ7">Last Updated</p>
              </div>
              <div className="framer-2hj3t0" data-framer-component-type="RichTextContainer" style={{ "transform": "none" }}>
                <p className="framer-text framer-styles-preset-1i01yr4" data-styles-preset="HaFviFY0f">
                  <strong className="framer-text">
                    <time dateTime="2026-02-24T00:00:00.000Z">Feb 24, 2026</time>
                  </strong>
                </p>
              </div>
            </div>
          </div>
        </div>
        <div className="framer-eimsoj" data-framer-name="Column">
          <div className="framer-vbtucf" data-framer-name="Content">
            <div className="framer-op2qui" data-framer-component-type="RichTextContainer" style={{ "transform": "none" }}>
              <p dir="auto" className="framer-text framer-styles-preset-1pni6u">
                <strong className="framer-text">{"These Exante Terms of Service (the “Terms of Service” or “Terms”) govern access to and use of the Exante Solutions Inc. (“Exante,” “we,” or “us”) website, applications, and other services provided by us (collectively, the “Service”). "}</strong>
              </p>
              <p dir="auto" className="framer-text framer-styles-preset-1pni6u">Website visitors are referred to in these terms as “Site Visitors” and individuals or entities who use the Service or create an account (“Account”) and their Authorized Users are collectively referred to as “Customers”. Customers and Site Visitors may be referred to in these Terms as “you” and “your” as applicable.</p>
              <p dir="auto" className="framer-text framer-styles-preset-1pni6u">{"These Terms are in addition to, and do not nullify, any other agreement between you and us or any other applicable terms and conditions found on the Service. "}</p>
              <h1 dir="auto" className="framer-text">
                <br className="framer-text trailing-break" />
              </h1>
              <h3 dir="auto" className="framer-text framer-styles-preset-7cz0c4">1. Acceptance of Terms</h3>
              <p dir="auto" className="framer-text framer-styles-preset-1pni6u">By using the Service, you as a Site Visitor or Customer accept and agree to follow and be bound by these Terms (whether on behalf of yourself or a legal entity you represent). You also agree to comply with all applicable laws and regulations, as well as all rules or restrictions that are posted on the Service. If you do not agree to these Terms, you are not authorized and must cease using the service immediately.</p>
              <h1 dir="auto" className="framer-text">
                <br className="framer-text trailing-break" />
              </h1>
              <h3 dir="auto" className="framer-text framer-styles-preset-7cz0c4">2. Aboute Exante</h3>
              <p dir="auto" className="framer-text framer-styles-preset-1pni6u">Exante provides AI-powered accounts receivable automation software that enables customers to automate billing workflows, generate invoices, monitor receivables, communicate with customers, and collect payments through integrations with third-party financial systems and payment processors (the “Service”).</p>
              <p dir="auto" className="framer-text framer-styles-preset-1pni6u">The Service may include AI agents and automated tools that analyze Customer Data and generate billing schedules, invoices, payment reminders, reports, or other financial outputs based on information provided by you.</p>
              <p dir="auto" className="framer-text framer-styles-preset-1pni6u">You acknowledge that Exante is not a bank, financial institution, accounting firm, or collection agency. The Service does not constitute financial, accounting, tax, legal, or investment advice. You remain solely responsible for reviewing and approving all invoices, communications, payment actions, and financial outputs generated by the Service before relying on them.</p>
              <p dir="auto" className="framer-text framer-styles-preset-1pni6u">Any automated outputs generated by AI features may contain errors and should be independently verified. Certain features of the Service utilize machine learning and artificial intelligence technologies to generate outputs based on Customer Data. You acknowledge that AI-generated outputs may be incomplete, inaccurate, or inappropriate and require human review. Exante does not guarantee the accuracy or reliability of AI outputs.</p>
              <h1 dir="auto" className="framer-text">
                <br className="framer-text trailing-break" />
              </h1>
              <h3 dir="auto" className="framer-text framer-styles-preset-7cz0c4">3. Eligibility</h3>
              <p dir="auto" className="framer-text framer-styles-preset-1pni6u">
                You agree that by using the Service you are at least 18 years of age and you are legally able to enter into a contract.
                <br className="framer-text" />
                <br className="framer-text" />
                {"If you are agreeing to these Terms on behalf of an organization or entity, you represent and warrant that you are authorized to agree to these Terms on that organization or entity’s behalf and bind them to these Terms (in which case, the references to \"you\" and \"your\" in these Terms, except for in this sentence, refer to that organization or entity)."}
                <br className="framer-text" />
                <br className="framer-text" />
                If Exante has previously prohibited you from accessing the Service, you are not permitted to access or use the Service.
              </p>
              <h1 dir="auto" className="framer-text">
                <br className="framer-text trailing-break" />
              </h1>
              <h3 dir="auto" className="framer-text framer-styles-preset-7cz0c4">4. Exante Account</h3>
              <p dir="auto" className="framer-text framer-styles-preset-1pni6u">
                When you create an Account to use or access certain portions of the Service, you must provide complete and accurate information as requested on the registration form, and you must maintain and update such information to keep it complete and accurate. You will also be asked to provide a username and password. You are entirely responsible for maintaining the confidentiality of your password, and are responsible for all activities (whether by you or by others) that occur under your password or Account. You may not use a third party’s Account, user name or password at any time, and you will not allow anyone other than Authorized Users to access or use the Service from your Account. You agree to notify Exante immediately of any unauthorized use of your account, user name or password. Exante shall not be liable for any losses you incur as a result of someone else’s use of your account or password, either with or without your knowledge. You may be held liable for any losses incurred by Exante, our affiliates, officers, directors, employees, consultants, agents and representatives due to someone else’s use of your account or password.
                <br className="framer-text" />
                <br className="framer-text" />
                You will promptly notify Exante of any suspected violation of these Terms by an Authorized User and will cooperate with Exante to address the suspected violation. Exante may suspend or terminate any Authorized User’s access to the Service upon notice to you in the event that Exante reasonably determines that such Authorized User violated these Terms.
              </p>
              <h1 dir="auto" className="framer-text">
                <br className="framer-text trailing-break" />
              </h1>
              <h3 dir="auto" className="framer-text framer-styles-preset-7cz0c4">5. Intellectual Property Rights</h3>
              <p dir="auto" className="framer-text framer-styles-preset-1pni6u">
                The Service is owned and operated by Exante Solutions Inc., and contains materials that are proprietary and are protected by copyright laws, international treaty provisions, trademarks, service marks, and other intellectual property laws and treaties. Except as otherwise expressly provided by Exante, none of the Service may be copied, reproduced, republished, downloaded, uploaded, posted, displayed, transmitted or distributed in any way and nothing on the Service shall be construed to confer any license under any of Exante’s intellectual property rights, whether by estoppel, implication or otherwise. Any rights not expressly granted in these Terms are reserved by Exante.
                <br className="framer-text" />
                <br className="framer-text" />
                The Service is also protected as a collective work or compilation under copyright and other laws and treaties. You agree to abide by all applicable copyright and other laws, as well as any additional copyright notices or restrictions contained on the Service. You acknowledge that the Service contains original works that have been developed, compiled, prepared, revised, selected, and arranged by Exante and others through the application of methods and standards of judgment developed and applied through the expenditure of substantial time, effort, and money and which constitute valuable intellectual property of Exante and such others. All present and future rights in and to trade secrets, patents, designs, copyrights, trademarks, database rights, service marks, know-how, and other intellectual property or other proprietary rights of any type, documentation, any improvements, design contributions, or derivative works thereto, and any knowledge or process related thereto, including rights in and to all applications and registrations relating to the Service, shall, as between you and Exante, at all times be and remain the sole and exclusive property of Exante.
                <br className="framer-text" />
                <br className="framer-text" />
                The trademarks, logos, taglines, and service marks displayed on the Service (collectively, the “Trademarks”) are registered and unregistered Trademarks of Exante and others. The Trademarks may not be used without Exante’s prior express written permission. Exante acknowledges the Trademarks of other organizations for their respective products or services mentioned on the Service. Other than as provided in these Terms, your use of the Trademarks, or any other Exante content, is strictly prohibited.
                <br className="framer-text" />
                <br className="framer-text" />
                Any software available for downloading through the Service or third-party websites or applications (the “Software”) is the copyrighted work of Exante and third-party providers. Use of the Software is governed by these Terms. Unauthorized reproduction or distribution of the Software is expressly prohibited by law, and may result in civil and criminal penalties. Violators may be prosecuted.
                <br className="framer-text" />
                <br className="framer-text" />
                Upon your acceptance of these Terms, we grant you a limited, non-exclusive, non-sublicensable, and non-assignable license to access and use the Service for your internal purposes and only as expressly permitted in these Terms. You shall not use or permit use of the Service for any illegal purpose or in any manner inconsistent with the provisions of these Terms. If you are or become a direct competitor of Exante, you may not access or use the Service without Exante’s explicit, advance, written consent, and then only for the purposes authorized in writing. Except as otherwise restricted by these Terms, Exante grants you permission on a non-exclusive, non-transferable, limited basis to display, copy, and download content and materials on the Service provided that you: (a) retain all copyright and other proprietary notices on the content and materials; (b) use them solely for internal use or in accordance with any applicable Exante Terms; and (c) do not modify them in any way. Any violation by you of the license provisions contained in this Section 5 may result in the immediate termination of your right to use the Service, as well as potential liability for copyright infringement or other claims depending on the circumstances.
              </p>
              <h1 dir="auto" className="framer-text">
                <br className="framer-text trailing-break" />
              </h1>
              <h3 dir="auto" className="framer-text framer-styles-preset-7cz0c4">7. User Comments, Feedback and Other Submissions</h3>
              <p dir="auto" className="framer-text framer-styles-preset-1pni6u">
                If, at our request, you send certain specific submissions or without a request from us you send creative ideas, suggestions, proposals, plans, or other materials, whether online, by email, by postal mail, or otherwise (collectively, “Comments”), you agree that we may, at any time, without restriction, edit, copy, publish, distribute, translate, and otherwise use in any medium any Comments that you forward to us. We are and shall be under no obligation (1) to maintain any Comments in confidence; (2) to pay compensation for any Comments; or (3) to respond to any Comments.
                <br className="framer-text" />
                <br className="framer-text" />
                We may, but have no obligation to, monitor, edit or remove content that we determine in our sole discretion are unlawful, offensive, threatening, libelous, defamatory, pornographic, obscene or otherwise objectionable or violates any party’s intellectual property or these Terms.
                <br className="framer-text" />
                <br className="framer-text" />
                You agree that your Comments will not violate any right of any third party, including copyright, trademark, privacy, personality or other personal or proprietary right. You further agree that your Comments will not contain libelous or otherwise unlawful, abusive or obscene material, or contain any computer virus or other malware that could in any way affect the operation of the Service or any related website. You may not use a false e-mail address, pretend to be someone other than yourself, or otherwise mislead us or third parties as to the origin of any Comments. You are solely responsible for any Comments you make and their accuracy. We take no responsibility and assume no liability for any Comments posted by you or any third party.
              </p>
              <h1 dir="auto" className="framer-text">
                <br className="framer-text trailing-break" />
              </h1>
              <h3 dir="auto" className="framer-text framer-styles-preset-7cz0c4">8. Use Restrictions</h3>
              <p dir="auto" className="framer-text framer-styles-preset-1pni6u">
                By using the Service, you specifically agree not to engage in any activity or transmit any information that, in our sole discretion:
                <br className="framer-text" />
                <br className="framer-text trailing-break" />
              </p>
              <ul dir="auto" className="framer-text">
                <li data-preset-tag="p" className="framer-text framer-styles-preset-1pni6u">
                  <p className="framer-text framer-styles-preset-1pni6u">Is illegal, or violates any federal, state, or local law or regulation;</p>
                </li>
                <li data-preset-tag="p" className="framer-text framer-styles-preset-1pni6u">
                  <p className="framer-text framer-styles-preset-1pni6u">Advocates illegal activity or discusses illegal activities with the intent to commit them;</p>
                </li>
                <li data-preset-tag="p" className="framer-text framer-styles-preset-1pni6u">
                  <p className="framer-text framer-styles-preset-1pni6u">Violates any third-party right, including, but not limited to, right of privacy, right of publicity, copyright, trademark, patent, trade secret, or any other intellectual property or proprietary rights;</p>
                </li>
                <li data-preset-tag="p" className="framer-text framer-styles-preset-1pni6u">
                  <p className="framer-text framer-styles-preset-1pni6u">Is harmful, threatening, abusive, harassing, tortious, indecent, defamatory, sexually explicit or pornographic, discriminatory, vulgar, profane, obscene, libelous, hate speech, violent or inciting violence, inflammatory, or otherwise objectionable;</p>
                </li>
                <li data-preset-tag="p" className="framer-text framer-styles-preset-1pni6u">
                  <p className="framer-text framer-styles-preset-1pni6u">Interferes with any other party’s use and enjoyment of the Service;</p>
                </li>
                <li data-preset-tag="p" className="framer-text framer-styles-preset-1pni6u">
                  <p className="framer-text framer-styles-preset-1pni6u">Attempts to impersonate another person or entity;</p>
                </li>
                <li data-preset-tag="p" className="framer-text framer-styles-preset-1pni6u">
                  <p className="framer-text framer-styles-preset-1pni6u">Is commercial in a way that violates these Terms, including but not limited to, using the Service for spam, surveys, contests, pyramid schemes, or other advertising materials;</p>
                </li>
                <li data-preset-tag="p" className="framer-text framer-styles-preset-1pni6u">
                  <p className="framer-text framer-styles-preset-1pni6u">Falsely states, misrepresents, or conceals your affiliation with another person or entity;</p>
                </li>
                <li data-preset-tag="p" className="framer-text framer-styles-preset-1pni6u">
                  <p className="framer-text framer-styles-preset-1pni6u">Accesses or uses the Account of another Customer or Paid Customer without permission;</p>
                </li>
                <li data-preset-tag="p" className="framer-text framer-styles-preset-1pni6u">
                  <p className="framer-text framer-styles-preset-1pni6u">Distributes computer viruses or other code, files, or programs that interrupt, destroy, or limit the functionality of any computer software or hardware or electronic communications equipment;</p>
                </li>
                <li data-preset-tag="p" className="framer-text framer-styles-preset-1pni6u">
                  <p className="framer-text framer-styles-preset-1pni6u">Interferes with, disrupts, disables, overburdens, or destroys the functionality or use of any features of the Service, or the servers or networks connected to the Service, or any of the Service;</p>
                </li>
                <li data-preset-tag="p" className="framer-text framer-styles-preset-1pni6u">
                  <p className="framer-text framer-styles-preset-1pni6u">“Hacks” or accesses without permission our proprietary or confidential records, those of another Customer, Paid Customer, or Site Visitor, or those of anyone else;</p>
                </li>
                <li data-preset-tag="p" className="framer-text framer-styles-preset-1pni6u">
                  <p className="framer-text framer-styles-preset-1pni6u">Improperly solicits personal or sensitive information from other Customers, Paid Customers or Site Visitors including without limitation address, credit card or financial account information, or passwords;</p>
                </li>
                <li data-preset-tag="p" className="framer-text framer-styles-preset-1pni6u">
                  <p className="framer-text framer-styles-preset-1pni6u">Decompiles, reverse engineers, disassembles, or otherwise attempts to derive source code from the Service, except as expressly permitted in these Terms or by law, unless and then only to the extent permitted by applicable law without consent;</p>
                </li>
                <li data-preset-tag="p" className="framer-text framer-styles-preset-1pni6u">
                  <p className="framer-text framer-styles-preset-1pni6u">Removes, circumvents, disables, damages, or otherwise interferes with security-related features, or features that enforce limitations on use of the Service;</p>
                </li>
                <li data-preset-tag="p" className="framer-text framer-styles-preset-1pni6u">
                  <p className="framer-text framer-styles-preset-1pni6u">Uses automated or manual means to violate the restrictions in any robot exclusion headers on the Service, if any, or bypasses or circumvents other measures employed to prevent or limit access, for example by engaging in practices such as “screen scraping,” “database scraping,” or any other activity with the purpose of obtaining lists of users or other information;</p>
                </li>
                <li data-preset-tag="p" className="framer-text framer-styles-preset-1pni6u">
                  <p className="framer-text framer-styles-preset-1pni6u">Modifies, copies, scrapes or crawls, displays, distributes, publishes, licenses, sells, rents, leases, lends, transfers, or otherwise commercializes any materials or content on the Service;</p>
                </li>
                <li data-preset-tag="p" className="framer-text framer-styles-preset-1pni6u">
                  <p className="framer-text framer-styles-preset-1pni6u">Uses the Service for benchmarking, or to compile information for a product or service;</p>
                </li>
                <li data-preset-tag="p" className="framer-text framer-styles-preset-1pni6u">
                  <p className="framer-text framer-styles-preset-1pni6u">Downloads (other than through page caching necessary for personal use, or as otherwise expressly permitted by these Terms), distributes, posts, transmits, performs, reproduces, broadcasts, duplicates, uploads, licenses, creates derivative works from, or offers for sale any content or other information contained on or obtained from or through the Service, by any means except as provided for in these Terms or with the prior written consent of Exante; or</p>
                </li>
                <li data-preset-tag="p" className="framer-text framer-styles-preset-1pni6u">
                  <p className="framer-text framer-styles-preset-1pni6u">Attempts to do any of the foregoing.</p>
                </li>
              </ul>
              <p dir="auto" className="framer-text framer-styles-preset-1pni6u">In addition, you shall not, and shall not permit others to, do the following with respect to the Service:</p>
              <ul dir="auto" className="framer-text">
                <li data-preset-tag="p" className="framer-text framer-styles-preset-1pni6u">
                  <p className="framer-text framer-styles-preset-1pni6u">Use the Service or allow access to it in a manner that circumvents contractual usage restrictions or that exceeds authorized use or usage metrics set forth in these Terms;</p>
                </li>
                <li data-preset-tag="p" className="framer-text framer-styles-preset-1pni6u">
                  <p className="framer-text framer-styles-preset-1pni6u">License, sub-license, sell, re-sell, rent, lease, transfer, distribute or time share or otherwise make any portion of the Service available for access by third parties except as otherwise expressly provided in these Terms;</p>
                </li>
                <li data-preset-tag="p" className="framer-text framer-styles-preset-1pni6u">
                  <p className="framer-text framer-styles-preset-1pni6u">Access or use the Service for the purpose of: (i) developing or operating products or services intended to be offered to third parties in competition with the Exante or (ii) allowing access to your Account by a direct competitor of Exante; or</p>
                </li>
                <li data-preset-tag="p" className="framer-text framer-styles-preset-1pni6u">
                  <p className="framer-text framer-styles-preset-1pni6u">
                    Frame the Service, place pop-up windows over its pages, or otherwise affect the display of its pages.
                    <br className="framer-text" />
                    <br className="framer-text" />
                    You acknowledge that we have no obligation to monitor your – or anyone else’s – access to or use of the Service for violations of these Terms, or to review or edit any content. However, we have the right to do so for the purpose of operating and improving the Service (including without limitation for fraud prevention, risk assessment, investigation and customer support purposes, analytics, and advertising), to ensure your compliance with these Terms and to comply with applicable law or the order or requirement of a court, consent decree, administrative agency or other governmental body.
                  </p>
                </li>
              </ul>
              <h1 dir="auto" className="framer-text">
                <br className="framer-text trailing-break" />
              </h1>
              <h3 dir="auto" className="framer-text framer-styles-preset-7cz0c4">9. Privacy</h3>
              <p dir="auto" className="framer-text framer-styles-preset-1pni6u">
                You acknowledge that, except as described in these Terms, the information you provide to us or that we collect will be used and protected as described in the Exante Privacy Policy.
                <br className="framer-text" />
                <br className="framer-text" />
                You acknowledge and agree that we may access, preserve, or share any of your information when we believe in good faith that such sharing is reasonably necessary to investigate, prevent, or take action regarding possible illegal activities or to comply with legal process (e.g. a subpoena or other legal process). We may also share your information in situations involving potential threats to the physical safety of any person, violations of the Exante Privacy Policy or our user agreements or terms; or to respond to the claims of violation of the rights of third parties and/or to protect the rights, property and safety of Exante, our employees, users, or the public. This may involve the sharing of your information with law enforcement, government agencies, courts, and/or other organizations.
              </p>
              <h1 dir="auto" className="framer-text">
                <br className="framer-text trailing-break" />
              </h1>
              <h3 dir="auto" className="framer-text framer-styles-preset-7cz0c4">10. Customer Data</h3>
              <p dir="auto" className="framer-text framer-styles-preset-1pni6u">You are responsible for the data and information that you or your Authorized Users input or upload into the Service (“Customer Data”). You are further responsible for obtaining any necessary rights and licenses for use of the Customer Data by you and Exante as contemplated in these Terms. You represent and warrant that you have the legal right and authority to access, use, and disclose to Exante any Customer Data.</p>
              <p dir="auto" className="framer-text framer-styles-preset-1pni6u">You authorize Exante to access, process, transmit, and use Customer Data as necessary to provide and improve the Service, including transmitting Customer Data to integrated third-party service providers at your direction. Exante will process Customer Data in accordance with the Exante Privacy Policy.</p>
              <p dir="auto" className="framer-text framer-styles-preset-1pni6u">The Service may integrate with third-party payment processors and financial service providers. Exante does not process payments directly and is not a bank, money transmitter, or payment processor. All payment transactions are processed by the applicable third-party provider under their respective terms and policies. You are solely responsible for establishing and maintaining your accounts with such third-party providers and ensuring such accounts remain in good standing.</p>
              <p dir="auto" className="framer-text framer-styles-preset-1pni6u">Exante is not responsible for payment processing errors, failed transactions, chargebacks, disputes, account suspensions, delays in funds availability, or the acts or omissions of any third-party service provider. Your use of such third-party services is subject to their applicable terms and policies.</p>
              <p dir="auto" className="framer-text framer-styles-preset-1pni6u">Exante does not use Customer Data to train generalized artificial intelligence models or foundation models for the benefit of other customers unless explicitly agreed in writing.</p>
              <h1 dir="auto" className="framer-text">
                <br className="framer-text trailing-break" />
              </h1>
              <h3 dir="auto" className="framer-text framer-styles-preset-7cz0c4">11. Customer Warranties</h3>
              <p dir="auto" className="framer-text framer-styles-preset-1pni6u">{"You hereby represent and warrant to Exante that: (a) you have all requisite rights and authority to use the Service under these Terms and to grant all applicable rights herein; (b) you are responsible for all use of the Service associated with its Account; (c) you are solely responsible for maintaining the confidentiality of its Account names and password(s); (d) you agree to immediately notify Exante of any unauthorized use of your Account of which you becomes aware; (e) you agree that Exante will not be liable for any losses incurred as a result of a third party's use of your Account, regardless of whether such use is with or without your knowledge and consent; (f) you will use the Service for lawful purposes only and subject to these Terms; (g) any information you submit to Exante is true, accurate, and correct; and (h) you will not attempt to gain unauthorized access to the System or the Service, other Accounts, computer systems, or networks under the control or responsibility of Exante through hacking, cracking, password mining, or any other unauthorized means."}</p>
              <h1 dir="auto" className="framer-text">
                <br className="framer-text trailing-break" />
              </h1>
              <h3 dir="auto" className="framer-text framer-styles-preset-7cz0c4">12. Fees</h3>
              <p dir="auto" className="framer-text framer-styles-preset-1pni6u">Exante reserves the right in the future to require payment of fees for certain or all aspects of the Service, change prices, or institute new charges, upon notice to you, which may be sent by email or posted on the Service. Your use of the Service following such notification constitutes your acceptance of any new or increased charges.</p>
              <h1 dir="auto" className="framer-text">
                <br className="framer-text trailing-break" />
              </h1>
              <h3 dir="auto" className="framer-text framer-styles-preset-7cz0c4">13. Modification of the Service</h3>
              <p dir="auto" className="framer-text framer-styles-preset-1pni6u">We reserve the right at any time to modify or discontinue the Service (or any part or content thereof) without notice. We shall not be liable to you or to any third party for any modification, suspension or discontinuance of the Service.</p>
              <h1 dir="auto" className="framer-text">
                <br className="framer-text trailing-break" />
              </h1>
              <h3 dir="auto" className="framer-text framer-styles-preset-7cz0c4">14. Term and Termination</h3>
              <p dir="auto" className="framer-text framer-styles-preset-1pni6u">
                These Terms are effective unless and until terminated by either you or us. If you are a user of the Free Plan, you may terminate your use of the Service at any time by ceasing further use of the Service. If you are a user of a Paid Plan, you may terminate your use of the Service in line with the terms specified in the Statement of Work signed in relation to the subscription. Exante is also free to terminate (or suspend access to) your use of the Service or your account, for any reason in our discretion, including your breach of these Terms. We have the sole right to decide whether you are in violation of any of the restrictions set forth in these Terms.
                <br className="framer-text" />
                <br className="framer-text" />
                If these Terms expire or are terminated for any reason: (a) any and all of your liabilities to Exante that have accrued before the effective date of the expiration or termination will survive; (b) licenses and use rights granted to you with respect to the Service and intellectual property will immediately terminate; (c) Exante’s obligation to provide any further services to you under these Terms will immediately terminate, except any such services that are expressly to be provided following expiration or termination of these Terms. Any other provisions that, by their nature, should survive termination of these Terms shall survive termination. By way of example, all of the following will survive termination: any obligation you have to pay us or indemnify us, any limitations on our liability, and any terms regarding ownership or intellectual property rights.
              </p>
              <h1 dir="auto" className="framer-text">
                <br className="framer-text trailing-break" />
              </h1>
              <h3 dir="auto" className="framer-text framer-styles-preset-7cz0c4">15. Third Party Content</h3>
              <p dir="auto" className="framer-text framer-styles-preset-1pni6u">We may provide, or third parties may provide, links to other third-party websites, services, or resources that are beyond our control. We make no representations or endorsements as to the quality, suitability, functionality, or legality of any third-party content to which links may be provided, and you hereby waive any claim you might have against us with respect to such services. EXANTE IS NOT RESPONSIBLE FOR THE CONTENT ON THE INTERNET OR WEB PAGES THAT ARE LOCATED OUTSIDE THE SERVICE OR POSTS OF USER CONTENT. Your correspondence or business dealings with, or participation in promotions of third parties found on or through the Service, including payment and delivery of related goods or services, and any other terms, conditions, warranties, or representations associated with such dealings, are solely between you and such third party or partner. You agree that we are not responsible or liable for any loss or damage of any sort incurred as the result of any such dealings or as the result of the presence of such partners or links to third-party websites or resources on the Service.</p>
              <h1 dir="auto" className="framer-text">
                <br className="framer-text trailing-break" />
              </h1>
              <h3 dir="auto" className="framer-text framer-styles-preset-7cz0c4">16. Warranties and Disclamers</h3>
              <p dir="auto" className="framer-text framer-styles-preset-1pni6u">
                THIS DISCLAIMER SECTION IS AN ESSENTIAL PART OF THESE TERMS.
                <br className="framer-text" />
                <br className="framer-text" />
                YOU ACKNOWLEDGE THAT YOU ARE USING THE SERVICE AT YOUR SOLE RISK. TO THE FULLEST EXTENT ALLOWED BY APPLICABLE LAW, THE SERVICE ARE PROVIDED ON AN “AS IS,” “WITH ALL FAULTS,” AND “AS AVAILABLE” BASIS WITHOUT WARRANTY OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE INCLUDING BUT NOT LIMITED TO THOSE OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, ACCURACY, COMPLETENESS, RELIABILITY, NON-INFRINGEMENT, OR ANY OTHER WARRANTY, CONDITION, GUARANTEE OR REPRESENTATION, WHETHER ORAL, IN WRITING OR IN ELECTRONIC FORM.
                <br className="framer-text" />
                <br className="framer-text" />
                EXANTE DOES NOT WARRANT THAT ACCESS TO OR USE OF THE SERVICE WILL FUNCTION WITHOUT INTERRUPTION, WILL MEET YOUR REQUIREMENTS, IS FREE OF MALICIOUS CODE OR THAT IT IS FREE OF ERRORS OR OMISSIONS, OR LOSS OR SECURITY BREACH OF TRANSMITTED INFORMATION, OR THAT NO VIRUSES WILL BE TRANSMITTED THROUGH ACCESS TO OR USE OF THE SERVICE.
                <br className="framer-text" />
                <br className="framer-text" />
                YOU ARE ADVISED TO SAFEGUARD YOUR DATA, TO USE CAUTION AND NOT TO RELY IN ANY WAY ON THE CORRECT FUNCTIONING OR PERFORMANCE OF THE SERVICE AND/OR ACCOMPANYING MATERIALS.
                <br className="framer-text" />
                <br className="framer-text" />
                CERTAIN STATE LAWS DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES. IF THESE LAWS APPLY TO YOU, SOME OR ALL OF THE FOREGOING DISCLAIMERS, EXCLUSIONS AND LIMITATIONS MAY NOT APPLY TO YOU, AND YOU MIGHT HAVE ADDITIONAL RIGHTS.
              </p>
              <h1 dir="auto" className="framer-text">
                <br className="framer-text trailing-break" />
              </h1>
              <h3 dir="auto" className="framer-text framer-styles-preset-7cz0c4">17. Indemnification</h3>
              <p dir="auto" className="framer-text framer-styles-preset-1pni6u">
                {"You will defend, indemnify, and hold us, our affiliates, officers, directors, employees, suppliers, consultants, and agents harmless from any and all third-party claims, liability, damages, and costs (including, but not limited to, attorneys' fees) arising from or related to, as applicable: (a) your access to and use of the Service; (b) violation of these Terms by you or your authorized Account user(s), as applicable; (c) infringement of any intellectual property or other right of any person or entity by you; (d) the nature and content of all Customer or Paid Customer data processed by the Service; or (e) any products or services purchased or obtained by you in connection with the Service."}
                <br className="framer-text" />
                <br className="framer-text" />
                Exante retains the exclusive right to settle, compromise, and pay, without your prior consent, any and all claims or causes of action that are brought against us. We reserve the right, at your expense, to assume the exclusive defense and control of any matter for which you are required to indemnify us and you agree to cooperate with our defense of these claims. You agree not to settle any matter in which we are named as a defendant and/or for which you have indemnity obligations without our prior written consent. We will use reasonable efforts to notify you of any such claim, action, or proceeding upon becoming aware of it.
                <br className="framer-text" />
                <br className="framer-text" />
                If you are a California resident, you waive California Civil Code Section 1542, which provides: A general release does not extend to claims that the creditor or releasing party does not know or suspect to exist in his or her favor at the time of executing the release, and that if known by him or her would have materially affected his or her settlement with the debtor or released party.
                <br className="framer-text" />
                <br className="framer-text" />
                If you are not a California resident, you waive your rights under any statute or common law principle similar to Section 1542 that governs your rights in the jurisdiction of your residence.
              </p>
              <h1 dir="auto" className="framer-text">
                <br className="framer-text trailing-break" />
              </h1>
              <h3 dir="auto" className="framer-text framer-styles-preset-7cz0c4">18. Limitations and Liability</h3>
              <p dir="auto" className="framer-text framer-styles-preset-1pni6u">
                TO THE FULLEST EXTENT ALLOWED BY APPLICABLE LAW, EXANTE, ITS AFFILIATES, ITS SUBSIDIARIES, AND ITS THIRD-PARTY SERVICE PROVIDERS SHALL NOT BE LIABLE TO YOU OR ANY THIRD PARTIES FOR ANY DIRECT, INDIRECT, PUNITIVE, SPECIAL, INCIDENTAL, CONSEQUENTIAL, OR EXEMPLARY DAMAGES (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF BUSINESS PROFITS, BUSINESS INTERRUPTION, OR LOSS OF DATA OR INFORMATION), HOWEVER IT ARISES (INCLUDING ATTORNEYS’ FEES AND ALL RELATED COSTS AND EXPENSES OF LITIGATION AND ARBITRATION, OR AT TRIAL OR ON APPEAL, IF ANY, WHETHER OR NOT LITIGATION OR ARBITRATION IS INSTITUTED), REGARDLESS OF THE TYPE OF CLAIM OR THE NATURE OF THE CAUSE OF ACTION, INCLUDING WITHOUT LIMITATION ANY CLAIM FOR BREACH OF CONTRACT, NEGLIGENCE, PERSONAL INJURY OR PROPERTY DAMAGE, ARISING FROM YOUR USE OF THE SERVICE, THIS AGREEMENT, OR ANY VIOLATION BY YOU OF ANY FEDERAL, STATE, OR LOCAL LAWS, STATUTES, RULES, OR REGULATIONS, EVEN IF EXANTE HAS BEEN PREVIOUSLY ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
                <br className="framer-text" />
                <br className="framer-text" />
                UNDER NO CIRCUMSTANCES WILL THE TOTAL AGGREGATE AMOUNT THAT EXANTE IS LIABLE TO YOU EXCEED THE GREATER OF (I) $100.00 OR (II) THE AMOUNTS PAID BY YOU TO EXANTE IN CONNECTION WITH THE SERVICE IN THE TWELVE (12) MONTH PERIOD PRECEDING THE EVENT ON WHICH YOUR CLAIM IS BASED. THE FOREGOING CAP ON LIABILITY SHALL NOT APPLY TO LIABILITY OF EXANTE FOR (1) DEATH, TANGIBLE PROPERTY DAMAGE, OR PERSONAL INJURY CAUSED BY EXANTE’S GROSS NEGLIGENCE OR FOR (2) ANY INJURY CAUSED BY EXANTE’S FRAUD OR FRAUDULENT MISREPRESENTATION.
                <br className="framer-text" />
                <br className="framer-text" />
                SOME STATES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF PUNITIVE, INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE PRIOR LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU. THE FOREGOING LIMITATIONS AND EXCLUSIONS OF LIABILITY AND DISCLAIMERS FORM AN ESSENTIAL BASIS OF THE BARGAIN BETWEEN THE PARTIES, AND EXANTE WOULD NOT ENTER INTO THIS AGREEMENT WITHOUT SUCH LIMITATIONS, EXCLUSIONS, AND DISCLAIMERS.
              </p>
              <h1 dir="auto" className="framer-text">
                <br className="framer-text trailing-break" />
              </h1>
              <h3 dir="auto" className="framer-text framer-styles-preset-7cz0c4">19. General</h3>
              <p dir="auto" className="framer-text framer-styles-preset-1pni6u">
                Electronic Communications. You agree to receive all communications, agreements, and notices that we provide in connection with the Service (“Communications”), including, but not limited to, Communications related to our delivery of the Service via electronic means, including by e-mail, text, in-product notifications, or by posting them on the Service. You agree that all Communications we provide to you electronically satisfy any legal requirement that such Communications be in writing or be delivered in a particular manner and you agree to keep your Account contact information current.
                <br className="framer-text" />
                <br className="framer-text" />
                Assignability. You may not assign your rights or obligations, or delegate your responsibilities hereunder without Exante’s prior written consent. If consent is given, these Terms will bind your successors and assigns. Any attempt by you to transfer your rights, duties, or obligations under these Terms except as expressly provided in these Terms is void. Exante may, at any time, freely assign its rights, duties, and obligations hereunder without notice to you.
                <br className="framer-text" />
                <br className="framer-text" />
                Force Majeure. Neither party will be liable hereunder by reason of any failure or delay in the performance of its obligations hereunder (except for the payment of money owed) on account of events beyond the reasonable control of such party, which may include without limitation denial-of-service attacks, strikes, shortages, riots, insurrection, fires, flood, storm, explosions, acts of God, war, terrorism, governmental action, labor conditions, earthquakes and material shortages, internet connectivity. The party affected by the force majeure event will provide notice to the other party within a commercially reasonable time and will use commercially reasonable efforts to resume performance as soon as practicable. Obligations not performed due to a force majeure event will be performed as soon as reasonably possible when the force majeure event concludes.
                <br className="framer-text" />
                <br className="framer-text" />
                Governing Law. These Terms and any dispute of any sort that might arise between you and Exante will be interpreted in accordance with the law of the State of California and the United States of America without regard to any conflict-of-law or other principles that provide for the application of the law of another jurisdiction. These Terms expressly exclude and disclaim the terms of the U.N. Convention on Contracts for the International Sale of Goods, which shall not apply to any transaction conducted through or otherwise involving the Service.
                <br className="framer-text" />
                <br className="framer-text" />
                Venue. Any claim or dispute that between you and Exante that arises out of or is related to the Service and is not subject to arbitration or eligible for small claims action, shall be decided exclusively by a court of competent jurisdiction located in San Francisco, California, and you hereby consent to, and waive all defense of lack of personal jurisdiction and forum non conveniens with respect to venue and jurisdiction in the state and federal courts of San Francisco, California.
                <br className="framer-text" />
                <br className="framer-text" />
                Entire Agreement. These Terms and any documents expressly incorporated by reference constitute the final, complete, and exclusive expression of the agreement between you and Exante regarding the Service provided under these Terms. These Terms supersede and the parties disclaim any reliance on previous oral and written communications with respect to the subject matter hereof and apply to the exclusion of any other terms that you seek to impose or incorporate, or which are implied by trade, custom, practice or course of dealing. Exante hereby rejects any additional or conflicting terms appearing in a purchase order or any other ordering materials submitted by you and conditions assent solely based on these Terms and conditions of these Terms as offered by Exante. Except as explicitly permitted in these Terms, no modification or amendment of these Terms shall be effective unless it is in writing and signed by an authorized agent of the party against whom the modification or amendment is being asserted.
                <br className="framer-text" />
                <br className="framer-text" />
                {"Trade Restrictions. You acknowledge that the Service and any related products, information, documentation, software, technology, technical data, and any derivatives thereof, that Exante makes available (collectively “Excluded Data”) are subject to the export control and sanctions laws and regulations of the United States and other countries that may prohibit or restrict access by certain persons or from certain countries or territories currently including, but not limited to, Cuban, Sudan, Iran, North Korea and Syria (\"Trade Restrictions”). You represent and warrant that you are not: (i) located in an embargoed country or territory, (ii) under the control of an entity organized in or a resident of an embargoed country or territory, (iii) listed on any U.S. government list of persons or entities with which U.S. persons are prohibited from transacting, including, but not limited to, OFAC’s List of Specially Designated Nationals and Other Blocked Persons, the U.S. State Department's Nonproliferation Sanctions lists, the U.S. Commerce Department’s Entity List or Denied Persons List located at https://www.export.gov/article?id=Consolidated-Screening-List; or (iv) subject to end destination export control regulations, such as, but not limited to, the U.S. Export Administration Regulations and U.S. Government EU Dual-Use Regulation EC 428/2009. You are solely responsible for complying with Trade Restrictions for all Excluded Data and any of its content transmitted through the Service."}
                <br className="framer-text" />
                <br className="framer-text" />
                Language and Translations. Exante may provide translations of these Terms or other terms or policies. Translations are provided for informational purposes and if there is an inconsistency or conflict between a translation and the English version, the English version will control.
                <br className="framer-text" />
                <br className="framer-text" />
                Waiver. The waiver by either you or Exante of any breach of any provision of these Terms does not waive any other breach. The failure of any party to these Terms to insist on strict performance of any covenant or obligation in accordance with these Terms will not be a waiver of such party’s right to demand strict compliance in the future, nor will the same be construed as a novation of these Terms.
                <br className="framer-text" />
                <br className="framer-text" />
                Severability. If any part of these Terms is found to be illegal, unenforceable, or invalid in any respect, the remaining portions of these Terms will remain in full force and effect. If any material limitation or restriction on the grant of any license to you under these Terms is found to be illegal, unenforceable, or invalid, the license will immediately terminate.
                <br className="framer-text" />
                <br className="framer-text" />
                Interpretation. Any ambiguities in the interpretation of these Terms shall not be construed against the drafting party.
                <br className="framer-text" />
                <br className="framer-text" />
                Headings. The headings used throughout these Terms are solely for the convenience of reference and are not to be used as an aid in the interpretation of these Terms.
                <br className="framer-text" />
                <br className="framer-text" />
                Consumer Complaints. California users are entitled to the following specific consumer rights notice: The Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs may be contacted in writing at 1625 North Market Blvd., Sacramento, CA 95834, or by telephone at (916) 445-1254 or (800) 952-5210.
              </p>
              <h1 dir="auto" className="framer-text">
                <br className="framer-text trailing-break" />
              </h1>
              <h3 dir="auto" className="framer-text framer-styles-preset-7cz0c4">20. Changes to Terms of Service</h3>
              <p dir="auto" className="framer-text framer-styles-preset-1pni6u">We reserve the right, at our sole discretion, to update, change or replace any part of these Terms. The most current version of the Terms will be posted on the Service and it is your responsibility to check our website periodically for changes. If the changes include material changes that affect your rights or obligations, we will notify you of the changes by reasonable means, which could include notification through the Service or via email.Your continued use of the Service following the effective date of any changes to these Terms constitutes acceptance of those changes. If you do not agree to the new Terms, you may not use the Service.</p>
              <h1 dir="auto" className="framer-text">
                <br className="framer-text trailing-break" />
              </h1>
              <h3 dir="auto" className="framer-text framer-styles-preset-7cz0c4">21. How to Contact Us</h3>
              <p dir="auto" className="framer-text framer-styles-preset-1pni6u">If you have any questions or concerns about the Service or these Terms, please contact us at team@exante.app.</p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
